package com.sit.entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Doctor entity class.
 * Tests all getters, setters, equals, hashCode, and toString generated by Lombok @Data.
 */
@DisplayName("Doctor Entity Tests")
class DoctorTest {

    private Doctor doctor;

    @BeforeEach
    void setUp() {
        doctor = new Doctor();
    }

    // ─── Constructor Tests ───────────────────────────────────────────────────

    @Test
    @DisplayName("Default constructor creates non-null Doctor instance")
    void constructor_default_createsNonNullInstance() {
        // Arrange & Act
        Doctor doc = new Doctor();

        // Assert
        assertNotNull(doc);
    }

    @Test
    @DisplayName("Default constructor initializes fields to null")
    void constructor_default_fieldsAreNull() {
        // Arrange & Act
        Doctor doc = new Doctor();

        // Assert
        assertNull(doc.getDocId());
        assertNull(doc.getDocName());
        assertNull(doc.getSpecialization());
        assertNull(doc.getIncome());
    }

    // ─── Setter / Getter Tests ────────────────────────────────────────────────

    @Test
    @DisplayName("setDocId and getDocId work correctly")
    void setDocId_validValue_getDocIdReturnsValue() {
        // Arrange
        Integer expectedId = 203;

        // Act
        doctor.setDocId(expectedId);

        // Assert
        assertEquals(expectedId, doctor.getDocId());
    }

    @Test
    @DisplayName("setDocId with null value stores null")
    void setDocId_nullValue_getDocIdReturnsNull() {
        // Arrange & Act
        doctor.setDocId(null);

        // Assert
        assertNull(doctor.getDocId());
    }

    @Test
    @DisplayName("setDocName and getDocName work correctly")
    void setDocName_validName_getDocNameReturnsName() {
        // Arrange
        String expectedName = "sairam";

        // Act
        doctor.setDocName(expectedName);

        // Assert
        assertEquals(expectedName, doctor.getDocName());
    }

    @Test
    @DisplayName("setDocName with null stores null")
    void setDocName_nullValue_getDocNameReturnsNull() {
        // Arrange & Act
        doctor.setDocName(null);

        // Assert
        assertNull(doctor.getDocName());
    }

    @Test
    @DisplayName("setDocName with empty string stores empty string")
    void setDocName_emptyString_getDocNameReturnsEmpty() {
        // Arrange & Act
        doctor.setDocName("");

        // Assert
        assertEquals("", doctor.getDocName());
    }

    @Test
    @DisplayName("setSpecialization and getSpecialization work correctly")
    void setSpecialization_validValue_getSpecializationReturnsValue() {
        // Arrange
        String expectedSpec = "MD_Cardio";

        // Act
        doctor.setSpecialization(expectedSpec);

        // Assert
        assertEquals(expectedSpec, doctor.getSpecialization());
    }

    @Test
    @DisplayName("setSpecialization with null stores null")
    void setSpecialization_nullValue_getSpecializationReturnsNull() {
        // Arrange & Act
        doctor.setSpecialization(null);

        // Assert
        assertNull(doctor.getSpecialization());
    }

    @Test
    @DisplayName("setIncome and getIncome work correctly")
    void setIncome_validValue_getIncomeReturnsValue() {
        // Arrange
        Double expectedIncome = 90000.00;

        // Act
        doctor.setIncome(expectedIncome);

        // Assert
        assertEquals(expectedIncome, doctor.getIncome());
    }

    @Test
    @DisplayName("setIncome with zero value stores zero")
    void setIncome_zeroValue_getIncomeReturnsZero() {
        // Arrange & Act
        doctor.setIncome(0.0);

        // Assert
        assertEquals(0.0, doctor.getIncome());
    }

    @Test
    @DisplayName("setIncome with negative value stores negative value")
    void setIncome_negativeValue_getIncomeReturnsNegative() {
        // Arrange & Act
        doctor.setIncome(-5000.00);

        // Assert
        assertEquals(-5000.00, doctor.getIncome());
    }

    @Test
    @DisplayName("setIncome with null stores null")
    void setIncome_nullValue_getIncomeReturnsNull() {
        // Arrange & Act
        doctor.setIncome(null);

        // Assert
        assertNull(doctor.getIncome());
    }

    // ─── Lombok @Data: equals() Tests ────────────────────────────────────────

    @Test
    @DisplayName("Two doctors with same fields are equal")
    void equals_samFields_returnsTrue() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("John");
        doc1.setSpecialization("Cardiology");
        doc1.setIncome(80000.0);

        Doctor doc2 = new Doctor();
        doc2.setDocId(1);
        doc2.setDocName("John");
        doc2.setSpecialization("Cardiology");
        doc2.setIncome(80000.0);

        // Act & Assert
        assertEquals(doc1, doc2);
    }

    @Test
    @DisplayName("Two doctors with different IDs are not equal")
    void equals_differentIds_returnsFalse() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("John");

        Doctor doc2 = new Doctor();
        doc2.setDocId(2);
        doc2.setDocName("John");

        // Act & Assert
        assertNotEquals(doc1, doc2);
    }

    @Test
    @DisplayName("Doctor is not equal to null")
    void equals_null_returnsFalse() {
        // Arrange
        Doctor doc = new Doctor();
        doc.setDocId(1);

        // Act & Assert
        assertNotEquals(null, doc);
    }

    @Test
    @DisplayName("Doctor is equal to itself")
    void equals_sameInstance_returnsTrue() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("Test");

        // Act & Assert
        assertEquals(doctor, doctor);
    }

    // ─── Lombok @Data: hashCode() Tests ──────────────────────────────────────

    @Test
    @DisplayName("Equal doctors have same hashCode")
    void hashCode_equalDoctors_samHashCode() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("John");
        doc1.setSpecialization("Cardiology");
        doc1.setIncome(80000.0);

        Doctor doc2 = new Doctor();
        doc2.setDocId(1);
        doc2.setDocName("John");
        doc2.setSpecialization("Cardiology");
        doc2.setIncome(80000.0);

        // Act & Assert
        assertEquals(doc1.hashCode(), doc2.hashCode());
    }

    @Test
    @DisplayName("hashCode is consistent across multiple calls")
    void hashCode_multipleInvocations_consistent() {
        // Arrange
        doctor.setDocId(5);
        doctor.setDocName("Alice");

        // Act
        int hash1 = doctor.hashCode();
        int hash2 = doctor.hashCode();

        // Assert
        assertEquals(hash1, hash2);
    }

    // ─── Lombok @Data: toString() Tests ──────────────────────────────────────

    @Test
    @DisplayName("toString returns non-null string")
    void toString_anyDoctor_returnsNonNull() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("sairam");
        doctor.setSpecialization("MD_Cardio");
        doctor.setIncome(90000.00);

        // Act
        String result = doctor.toString();

        // Assert
        assertNotNull(result);
    }

    @Test
    @DisplayName("toString contains docName")
    void toString_withDocName_containsDocName() {
        // Arrange
        doctor.setDocName("sairam");

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("sairam"));
    }

    @Test
    @DisplayName("toString contains specialization")
    void toString_withSpecialization_containsSpecialization() {
        // Arrange
        doctor.setSpecialization("MD_Cardio");

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("MD_Cardio"));
    }

    // ─── Full Object Population Test ─────────────────────────────────────────

    @Test
    @DisplayName("Fully populated Doctor retains all field values")
    void doctor_fullyPopulated_allFieldsRetained() {
        // Arrange
        Integer id = 203;
        String name = "Dr. Smith";
        String spec = "Neurology";
        Double income = 120000.00;

        // Act
        doctor.setDocId(id);
        doctor.setDocName(name);
        doctor.setSpecialization(spec);
        doctor.setIncome(income);

        // Assert
        assertAll("Doctor fields",
                () -> assertEquals(id, doctor.getDocId()),
                () -> assertEquals(name, doctor.getDocName()),
                () -> assertEquals(spec, doctor.getSpecialization()),
                () -> assertEquals(income, doctor.getIncome())
        );
    }
}
