package com.sit.entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Doctor entity class.
 * Tests all getters, setters, equals, hashCode, and toString generated by Lombok @Data.
 */
@DisplayName("Doctor Entity Tests")
class DoctorTest {

    private Doctor doctor;

    @BeforeEach
    void setUp() {
        doctor = new Doctor();
    }

    // ─── Constructor Tests ────────────────────────────────────────────────────

    @Test
    @DisplayName("Default constructor creates non-null Doctor instance")
    void testDefaultConstructor_createsNonNullInstance() {
        // Arrange & Act
        Doctor doc = new Doctor();

        // Assert
        assertNotNull(doc);
    }

    @Test
    @DisplayName("Default constructor initializes fields to null")
    void testDefaultConstructor_fieldsAreNull() {
        // Arrange & Act
        Doctor doc = new Doctor();

        // Assert
        assertNull(doc.getDocId());
        assertNull(doc.getDocName());
        assertNull(doc.getSpecialization());
        assertNull(doc.getIncome());
    }

    // ─── Setter / Getter Tests ────────────────────────────────────────────────

    @Test
    @DisplayName("setDocId and getDocId work correctly")
    void testSetAndGetDocId() {
        // Arrange
        Integer expectedId = 101;

        // Act
        doctor.setDocId(expectedId);

        // Assert
        assertEquals(expectedId, doctor.getDocId());
    }

    @Test
    @DisplayName("setDocName and getDocName work correctly")
    void testSetAndGetDocName() {
        // Arrange
        String expectedName = "Dr. John Smith";

        // Act
        doctor.setDocName(expectedName);

        // Assert
        assertEquals(expectedName, doctor.getDocName());
    }

    @Test
    @DisplayName("setSpecialization and getSpecialization work correctly")
    void testSetAndGetSpecialization() {
        // Arrange
        String expectedSpec = "MD_Cardio";

        // Act
        doctor.setSpecialization(expectedSpec);

        // Assert
        assertEquals(expectedSpec, doctor.getSpecialization());
    }

    @Test
    @DisplayName("setIncome and getIncome work correctly")
    void testSetAndGetIncome() {
        // Arrange
        Double expectedIncome = 90000.00;

        // Act
        doctor.setIncome(expectedIncome);

        // Assert
        assertEquals(expectedIncome, doctor.getIncome());
    }

    @Test
    @DisplayName("setDocName with null value stores null")
    void testSetDocName_withNull_storesNull() {
        // Arrange
        doctor.setDocName("Initial Name");

        // Act
        doctor.setDocName(null);

        // Assert
        assertNull(doctor.getDocName());
    }

    @Test
    @DisplayName("setSpecialization with null value stores null")
    void testSetSpecialization_withNull_storesNull() {
        // Arrange
        doctor.setSpecialization("Cardiology");

        // Act
        doctor.setSpecialization(null);

        // Assert
        assertNull(doctor.getSpecialization());
    }

    @Test
    @DisplayName("setIncome with null value stores null")
    void testSetIncome_withNull_storesNull() {
        // Arrange
        doctor.setIncome(50000.00);

        // Act
        doctor.setIncome(null);

        // Assert
        assertNull(doctor.getIncome());
    }

    @Test
    @DisplayName("setDocId with zero value stores zero")
    void testSetDocId_withZero_storesZero() {
        // Arrange & Act
        doctor.setDocId(0);

        // Assert
        assertEquals(0, doctor.getDocId());
    }

    @Test
    @DisplayName("setIncome with zero value stores zero")
    void testSetIncome_withZero_storesZero() {
        // Arrange & Act
        doctor.setIncome(0.0);

        // Assert
        assertEquals(0.0, doctor.getIncome());
    }

    @Test
    @DisplayName("setIncome with negative value stores negative")
    void testSetIncome_withNegativeValue_storesNegative() {
        // Arrange & Act
        doctor.setIncome(-1000.00);

        // Assert
        assertEquals(-1000.00, doctor.getIncome());
    }

    // ─── Equals Tests (Lombok @Data) ─────────────────────────────────────────

    @Test
    @DisplayName("Two doctors with same fields are equal")
    void testEquals_sameDoctors_areEqual() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("sairam");
        doc1.setSpecialization("MD_Cardio");
        doc1.setIncome(90000.00);

        Doctor doc2 = new Doctor();
        doc2.setDocId(1);
        doc2.setDocName("sairam");
        doc2.setSpecialization("MD_Cardio");
        doc2.setIncome(90000.00);

        // Act & Assert
        assertEquals(doc1, doc2);
    }

    @Test
    @DisplayName("Two doctors with different IDs are not equal")
    void testEquals_differentDocId_notEqual() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("sairam");

        Doctor doc2 = new Doctor();
        doc2.setDocId(2);
        doc2.setDocName("sairam");

        // Act & Assert
        assertNotEquals(doc1, doc2);
    }

    @Test
    @DisplayName("Doctor is not equal to null")
    void testEquals_withNull_notEqual() {
        // Arrange
        doctor.setDocId(1);

        // Act & Assert
        assertNotEquals(null, doctor);
    }

    @Test
    @DisplayName("Doctor equals itself (reflexive)")
    void testEquals_sameInstance_isEqual() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("sairam");

        // Act & Assert
        assertEquals(doctor, doctor);
    }

    // ─── HashCode Tests (Lombok @Data) ───────────────────────────────────────

    @Test
    @DisplayName("Two equal doctors have same hashCode")
    void testHashCode_equalDoctors_sameHashCode() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("sairam");
        doc1.setSpecialization("MD_Cardio");
        doc1.setIncome(90000.00);

        Doctor doc2 = new Doctor();
        doc2.setDocId(1);
        doc2.setDocName("sairam");
        doc2.setSpecialization("MD_Cardio");
        doc2.setIncome(90000.00);

        // Act & Assert
        assertEquals(doc1.hashCode(), doc2.hashCode());
    }

    @Test
    @DisplayName("hashCode is consistent across multiple calls")
    void testHashCode_consistentAcrossMultipleCalls() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("sairam");

        // Act
        int hash1 = doctor.hashCode();
        int hash2 = doctor.hashCode();

        // Assert
        assertEquals(hash1, hash2);
    }

    // ─── ToString Tests (Lombok @Data) ───────────────────────────────────────

    @Test
    @DisplayName("toString returns non-null string")
    void testToString_returnsNonNull() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("sairam");

        // Act
        String result = doctor.toString();

        // Assert
        assertNotNull(result);
    }

    @Test
    @DisplayName("toString contains class name Doctor")
    void testToString_containsClassName() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("sairam");

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("Doctor"));
    }

    @Test
    @DisplayName("toString contains docName value")
    void testToString_containsDocName() {
        // Arrange
        doctor.setDocName("sairam");

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("sairam"));
    }

    @Test
    @DisplayName("toString contains specialization value")
    void testToString_containsSpecialization() {
        // Arrange
        doctor.setSpecialization("MD_Cardio");

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("MD_Cardio"));
    }

    // ─── Full Object Population Tests ────────────────────────────────────────

    @Test
    @DisplayName("Fully populated Doctor has all fields set correctly")
    void testFullyPopulatedDoctor_allFieldsCorrect() {
        // Arrange
        Integer id = 203;
        String name = "Dr. Alice";
        String spec = "Neurology";
        Double income = 120000.00;

        // Act
        doctor.setDocId(id);
        doctor.setDocName(name);
        doctor.setSpecialization(spec);
        doctor.setIncome(income);

        // Assert
        assertAll("Doctor fields",
                () -> assertEquals(id, doctor.getDocId()),
                () -> assertEquals(name, doctor.getDocName()),
                () -> assertEquals(spec, doctor.getSpecialization()),
                () -> assertEquals(income, doctor.getIncome())
        );
    }

    @Test
    @DisplayName("Doctor with large income value stores correctly")
    void testSetIncome_withLargeValue_storesCorrectly() {
        // Arrange
        Double largeIncome = Double.MAX_VALUE;

        // Act
        doctor.setIncome(largeIncome);

        // Assert
        assertEquals(Double.MAX_VALUE, doctor.getIncome());
    }

    @Test
    @DisplayName("Doctor with empty string docName stores correctly")
    void testSetDocName_withEmptyString_storesCorrectly() {
        // Arrange & Act
        doctor.setDocName("");

        // Assert
        assertEquals("", doctor.getDocName());
    }

    @Test
    @DisplayName("Doctor with empty string specialization stores correctly")
    void testSetSpecialization_withEmptyString_storesCorrectly() {
        // Arrange & Act
        doctor.setSpecialization("");

        // Assert
        assertEquals("", doctor.getSpecialization());
    }
}
