package com.sit.entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Doctor entity class.
 * Tests all getters, setters, equals, hashCode, and toString generated by Lombok @Data.
 */
@DisplayName("Doctor Entity Tests")
class DoctorTest {

    private Doctor doctor;

    @BeforeEach
    void setUp() {
        doctor = new Doctor();
    }

    // ─── Constructor Tests ────────────────────────────────────────────────────

    @Test
    @DisplayName("Default constructor creates non-null Doctor instance")
    void defaultConstructor_shouldCreateNonNullInstance() {
        // Arrange & Act
        Doctor doc = new Doctor();

        // Assert
        assertNotNull(doc);
    }

    @Test
    @DisplayName("Default constructor initializes fields to null")
    void defaultConstructor_shouldInitializeFieldsToNull() {
        // Arrange & Act
        Doctor doc = new Doctor();

        // Assert
        assertNull(doc.getDocId());
        assertNull(doc.getDocName());
        assertNull(doc.getSpecialization());
        assertNull(doc.getIncome());
    }

    // ─── Setter / Getter Tests ────────────────────────────────────────────────

    @Test
    @DisplayName("setDocId and getDocId work correctly")
    void setDocId_shouldStoreAndReturnCorrectValue() {
        // Arrange
        Integer expectedId = 101;

        // Act
        doctor.setDocId(expectedId);

        // Assert
        assertEquals(expectedId, doctor.getDocId());
    }

    @Test
    @DisplayName("setDocName and getDocName work correctly")
    void setDocName_shouldStoreAndReturnCorrectValue() {
        // Arrange
        String expectedName = "Dr. John Smith";

        // Act
        doctor.setDocName(expectedName);

        // Assert
        assertEquals(expectedName, doctor.getDocName());
    }

    @Test
    @DisplayName("setSpecialization and getSpecialization work correctly")
    void setSpecialization_shouldStoreAndReturnCorrectValue() {
        // Arrange
        String expectedSpec = "MD_Cardio";

        // Act
        doctor.setSpecialization(expectedSpec);

        // Assert
        assertEquals(expectedSpec, doctor.getSpecialization());
    }

    @Test
    @DisplayName("setIncome and getIncome work correctly")
    void setIncome_shouldStoreAndReturnCorrectValue() {
        // Arrange
        Double expectedIncome = 90000.00;

        // Act
        doctor.setIncome(expectedIncome);

        // Assert
        assertEquals(expectedIncome, doctor.getIncome());
    }

    @Test
    @DisplayName("setDocId with null value stores null")
    void setDocId_withNull_shouldStoreNull() {
        // Arrange
        doctor.setDocId(999);

        // Act
        doctor.setDocId(null);

        // Assert
        assertNull(doctor.getDocId());
    }

    @Test
    @DisplayName("setDocName with null value stores null")
    void setDocName_withNull_shouldStoreNull() {
        // Arrange
        doctor.setDocName("SomeName");

        // Act
        doctor.setDocName(null);

        // Assert
        assertNull(doctor.getDocName());
    }

    @Test
    @DisplayName("setSpecialization with null value stores null")
    void setSpecialization_withNull_shouldStoreNull() {
        // Arrange
        doctor.setSpecialization("Cardiology");

        // Act
        doctor.setSpecialization(null);

        // Assert
        assertNull(doctor.getSpecialization());
    }

    @Test
    @DisplayName("setIncome with null value stores null")
    void setIncome_withNull_shouldStoreNull() {
        // Arrange
        doctor.setIncome(50000.00);

        // Act
        doctor.setIncome(null);

        // Assert
        assertNull(doctor.getIncome());
    }

    @Test
    @DisplayName("setIncome with zero value stores zero")
    void setIncome_withZero_shouldStoreZero() {
        // Arrange & Act
        doctor.setIncome(0.0);

        // Assert
        assertEquals(0.0, doctor.getIncome());
    }

    @Test
    @DisplayName("setIncome with negative value stores negative")
    void setIncome_withNegativeValue_shouldStoreNegative() {
        // Arrange & Act
        doctor.setIncome(-1000.00);

        // Assert
        assertEquals(-1000.00, doctor.getIncome());
    }

    @Test
    @DisplayName("setDocName with empty string stores empty string")
    void setDocName_withEmptyString_shouldStoreEmptyString() {
        // Arrange & Act
        doctor.setDocName("");

        // Assert
        assertEquals("", doctor.getDocName());
    }

    // ─── Equals and HashCode Tests (Lombok @Data) ─────────────────────────────

    @Test
    @DisplayName("Two doctors with same fields are equal")
    void equals_withSameFields_shouldReturnTrue() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("Alice");
        doc1.setSpecialization("Cardiology");
        doc1.setIncome(80000.00);

        Doctor doc2 = new Doctor();
        doc2.setDocId(1);
        doc2.setDocName("Alice");
        doc2.setSpecialization("Cardiology");
        doc2.setIncome(80000.00);

        // Act & Assert
        assertEquals(doc1, doc2);
    }

    @Test
    @DisplayName("Two doctors with different IDs are not equal")
    void equals_withDifferentIds_shouldReturnFalse() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("Alice");

        Doctor doc2 = new Doctor();
        doc2.setDocId(2);
        doc2.setDocName("Alice");

        // Act & Assert
        assertNotEquals(doc1, doc2);
    }

    @Test
    @DisplayName("Two doctors with same fields have same hashCode")
    void hashCode_withSameFields_shouldBeEqual() {
        // Arrange
        Doctor doc1 = new Doctor();
        doc1.setDocId(1);
        doc1.setDocName("Alice");
        doc1.setSpecialization("Cardiology");
        doc1.setIncome(80000.00);

        Doctor doc2 = new Doctor();
        doc2.setDocId(1);
        doc2.setDocName("Alice");
        doc2.setSpecialization("Cardiology");
        doc2.setIncome(80000.00);

        // Act & Assert
        assertEquals(doc1.hashCode(), doc2.hashCode());
    }

    @Test
    @DisplayName("Doctor equals itself (reflexive)")
    void equals_withSameInstance_shouldReturnTrue() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("Alice");

        // Act & Assert
        assertEquals(doctor, doctor);
    }

    @Test
    @DisplayName("Doctor is not equal to null")
    void equals_withNull_shouldReturnFalse() {
        // Arrange
        doctor.setDocId(1);

        // Act & Assert
        assertNotEquals(null, doctor);
    }

    // ─── toString Tests (Lombok @Data) ────────────────────────────────────────

    @Test
    @DisplayName("toString returns non-null string")
    void toString_shouldReturnNonNullString() {
        // Arrange
        doctor.setDocId(1);
        doctor.setDocName("Alice");
        doctor.setSpecialization("Cardiology");
        doctor.setIncome(80000.00);

        // Act
        String result = doctor.toString();

        // Assert
        assertNotNull(result);
    }

    @Test
    @DisplayName("toString contains docName value")
    void toString_shouldContainDocName() {
        // Arrange
        doctor.setDocName("Dr. Alice");

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("Dr. Alice"));
    }

    @Test
    @DisplayName("toString contains specialization value")
    void toString_shouldContainSpecialization() {
        // Arrange
        doctor.setSpecialization("Neurology");

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("Neurology"));
    }

    @Test
    @DisplayName("toString contains income value")
    void toString_shouldContainIncome() {
        // Arrange
        doctor.setIncome(75000.0);

        // Act
        String result = doctor.toString();

        // Assert
        assertTrue(result.contains("75000.0"));
    }

    // ─── Full Object Population Test ──────────────────────────────────────────

    @Test
    @DisplayName("Fully populated Doctor has all fields set correctly")
    void fullyPopulatedDoctor_shouldHaveAllFieldsSet() {
        // Arrange
        Integer id = 203;
        String name = "sairam";
        String spec = "MD_Cardio";
        Double income = 90000.00;

        // Act
        doctor.setDocId(id);
        doctor.setDocName(name);
        doctor.setSpecialization(spec);
        doctor.setIncome(income);

        // Assert
        assertAll("Doctor fields",
                () -> assertEquals(id, doctor.getDocId()),
                () -> assertEquals(name, doctor.getDocName()),
                () -> assertEquals(spec, doctor.getSpecialization()),
                () -> assertEquals(income, doctor.getIncome())
        );
    }

    @Test
    @DisplayName("Doctor fields can be updated after initial set")
    void doctorFields_canBeUpdatedAfterInitialSet() {
        // Arrange
        doctor.setDocName("Initial Name");
        doctor.setIncome(50000.00);

        // Act
        doctor.setDocName("Updated Name");
        doctor.setIncome(60000.00);

        // Assert
        assertEquals("Updated Name", doctor.getDocName());
        assertEquals(60000.00, doctor.getIncome());
    }
}
